name: Cleanup
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}
jobs:
  images:
    runs-on: ubuntu-latest
    name: cleanup
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        projects:
          - vjp-cloud-desktops-pr
          - vjp-cloud-desktops
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/76410834219/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'gha-vjftw-cloud-desktops-main@vjp-github-actions.iam.gserviceaccount.com'

      - name: run cleanup
        run: |-
          gcloud config set project "${GCP_PROJECT_ID}"
          ./pleasew run //build:cleanup
        env:
          GCP_PROJECT_ID: ${{ matrix.flavour }}
