name: Pull Request
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2

      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/76410834219/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'ghapr-vjftw-cloud-desktops@vjp-github-actions.iam.gserviceaccount.com'

      - name: Create infrastructure
        if: success()
        run: |-
          ./pleasew -p -v2 run ///third_party/repo/org-infra//build/ci/github:terraform_workspace -- \
            apply \
            --workspace_name="pr" \
            --please_target="//deployment/packer:packer"

  build:
    runs-on: ubuntu-latest
    needs: [terraform]
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        flavour:
          - arch:xfce4
          - debian:xfce4
          - debian/kali:xfce4
    
    name: ${{ matrix.flavour }}
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/76410834219/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'ghapr-vjftw-cloud-desktops@vjp-github-actions.iam.gserviceaccount.com'

      - name: run packer build
        run: ./pleasew run "//flavours/${{ matrix.flavour }}_build"
        env:
          GCP_PROJECT_ID: vjp-cloud-desktops-pr

      - uses: actions/upload-artifact@v2
        with:
          name: packer-manifests
          path: plz-out/**/packer-manifest.json

  clean_up:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/76410834219/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'ghapr-vjftw-cloud-desktops@vjp-github-actions.iam.gserviceaccount.com'

      - uses: actions/download-artifact@v2
        with:
          path: plz-out/

      - name: Cleanup images created in PR
        run: ./pleasew run //build:pr_cleanup
        env:
          GCP_PROJECT_ID: vjp-cloud-desktops-pr
