name: Release
on:
  schedule:
    - cron: '0 0 * * FRI'
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        flavour:
          - debian/xfce4
          - debian/kali/xfce4
    name: ${{ matrix.flavour }}
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: install packer
        run: scripts/ci-install-packer.sh

      - name: Setup GCP credentials
        uses: google-github-actions/setup-gcloud@master
        with: 
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_FILE_contents }}
          export_default_credentials: true

      - name: run packer build
        run: scripts/build.sh "${{ matrix.flavour }}"

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Setup GCP credentials
        uses: google-github-actions/setup-gcloud@master
        with: 
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_FILE_contents }}
          export_default_credentials: true

      - name: Generate Changelog
        run: ./scripts/release-body.sh ${{ github.workspace }}-RELEASE_BODY.txt

      - name: Compute the release tag
        run: |
          echo "release_tag=$(./scripts/version.sh)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-RELEASE_BODY.txt
          target_commitish: master
          draft: false
          prerelease: false
          tag_name: ${{ env.release_tag }}
