name: Release
on:
  schedule:
    - cron: '0 0 * * FRI'
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        flavour:
          - debian:xfce4
          - debian/kali:xfce4

    name: ${{ matrix.flavour }}
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Setup GCP credentials
        uses: google-github-actions/setup-gcloud@master
        with: 
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_FILE_contents }}
          export_default_credentials: true

      - name: run packer build
        run: ./pleasew run "//flavours/${{ matrix.flavour }}_build"
        env:
          GCP_PROJECT_ID: vjftw-images

      - uses: actions/upload-artifact@v2
        with:
          name: packer-manifest-${{ job.container.id }}
          path: plz-out/**/packer-manifest.json

      - name: make images public
        run: ./pleasew run //build:publicise
        env:
          GCP_PROJECT_ID: vjftw-images

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Setup GCP credentials
        uses: google-github-actions/setup-gcloud@master
        with: 
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_FILE_contents }}
          export_default_credentials: true

      - uses: actions/download-artifact@v2
        with:
          path: plz-out/

      - name: Generate Release body
        run: ./pleasew run //build:release_body -- ${{ github.workspace }}-RELEASE_BODY.txt
        env:
          GCP_PROJECT_ID: vjftw-images

      - name: Compute the release tag
        run: |
          echo "release_tag=$(./pleasew run //build:version)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-RELEASE_BODY.txt
          target_commitish: master
          draft: false
          prerelease: false
          tag_name: ${{ env.release_tag }}
